#!/bin/bash

# You cannot see the Khan Academy exercises or JSAV code objects
# in a browser directed to a local file unless you run a web
# server. In case you are on a machine (such as your own PC) without a
# web server running, here is a little python-based web server.
# You only need to have Python installed to run this.
# After invoking this script from ~OpenDSA, point your web browser to:
# http://127.0.0.1:8080/
# python -m SimpleHTTPServer

echo "This script is not needed anymore."
echo "Use 'make Webserver' or 'python3 server.py' instead"
exit

unameOut="$(uname -s)"
echo System is: "${unameOut}"
case "${unameOut}" in
    MINGW*)  python3 server.py;;
    CYGWIN*) python3 server.py;;
    Linux*)  python3 server.py;;
    Darwin*) python3 server.py;;
    *)       python3 server.py

esac
