(function ($) {
  var jsav = new JSAV("container");
  var ll = new SkipList(jsav);
  jsav.umsg("We start with an empty SkipList");
  jsav.displayInit();
  ll.insert(new KVPair(1, "A"));
  jsav.umsg("adding one key-value pair (1, A) of depth 0 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(9, "B"));
  jsav.umsg("adding another key-value pair (2, B) of depth 1 to the SkipList");
  //jsav.displayInit();
  jsav.step();
  ll.insert(new KVPair(3, "C"));
  jsav.umsg("adding another key-value pair (0, C) of depth 0 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(0, "D"), null, 1);
  //jsav.displayInit();
  jsav.umsg("adding another key-value pair (0, C) of depth 0 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(0, "D"));
  jsav.umsg("adding another key-value pair (3, C) of depth 0 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(4, "D"));
  jsav.umsg("adding another key-value pair (4, D) of depth 1 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(5, "E"));
  jsav.umsg("adding another key-value pair (5, E) of depth 0 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(6, "F"));
  jsav.umsg("adding another key-value pair (6, F) of depth 1 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(7, "G"));
  jsav.umsg("adding another key-value pair (7, G) of depth 0 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(8, "H"));
  jsav.umsg("adding another key-value pair (8, G) of depth 1 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(1, "H"));
  jsav.umsg("adding another key-value pair (8, G) of depth 1 to the SkipList");
  jsav.step();
  ll.insert(new KVPair(2, "G"));
  jsav.umsg("adding another key-value pair (2, G) of depth 1 to the SkipList");
  jsav.step();
  //jsav.displayInit();
  //jsav.step();
  ll.search(7);
  jsav.step();
  ll.search(12);
  jsav.step();
  ll.removeKey(1);
  jsav.umsg("removing key 1");
  jsav.step();
  ll.removeKey(9);
  jsav.umsg("removing key 9");
  jsav.step();
  ll.removeKey(3);
  jsav.umsg("removing key 3");
  jsav.step();
  ll.removeKey(0);
  jsav.umsg("removing key 0");
  jsav.step();
  ll.removeKey(2);
  jsav.umsg("removing key 2");
  jsav.step();
  ll.removeKey(4);
  jsav.umsg("removing key 4");
  jsav.step();
  jsav.recorded();
}(jQuery));
