[theme]
inherit = basic
stylesheet = groundwork.css
pygments_style = sphinx

[options]
sidebar_width = 220px
stickysidebar = True
stickysidebarscrollable = False
touch_icon = ""
github_fork = ""
github_user = ""
contribute = False
github_ribbon_color = white_ffffff
show_source = false
show_search = false
show_relations = false
show_header = false
show_copyright = false
